[package]
name = "libiconfig"
version = "0.1"
lean_version = "khoek/klean:3.4.4"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "8c385bc404640d7f131ffaf2611eeeb7943dc7f6"}
